app/views/super_admin.py
from flask import Blueprint, render_template, session, redirect, url_for, request, jsonify
from app.utils.role_util import *
from app.db_controllers.super_admin_controller import *
from app.db_controllers.main_db_controller import *
from app.db_controllers.helper import *
from app.data.grade_breakdown import data as grade_breakdown
from app.data.formula import formula_list
from app.db_controllers.logging import *

super_admin = Blueprint('super_admin', __name__, url_prefix="/super-admin")

@super_admin.route('/')
def login():
    try:
        if session.get("super_admin_id"):
            return redirect(url_for("super_admin.dashboard"))
        elif session.get("admin_id"):
            return redirect(url_for("admin.dashboard"))
        elif session.get("contributor_id"):
            return redirect(url_for("contributor.dashboard"))
        elif session.get("graphics_id"):
            return redirect(url_for("graphics.dashboard"))
        return render_template("/super_admin/login/login.html")
    except Exception as e:
        log_error("view", "super_admin", str(e), "login")
        return jsonify({
            "message": str(e),
            "status": "error"
        }), 400

@super_admin.route("/dashboard")
@required_role_as_super_admin()
def dashboard():
    try:
        session["question_id_list"] = None
        user_data = get_user_document_data(session.get('super_admin_id'))
        leaderboard_data = get_admin_review_stats()
        chart_data = get_cumulative_chart_data()
        line_chart_data = get_chart_data(session.get('super_admin_id'))
        sidebar_filter_based_on_requirement = firebase_get_approved_question_count()
        return render_template( "/super_admin/dashboard/dashboard.html",
                                grade_breakdown=grade_breakdown,
                                user_data=user_data,
                                leaderboard_data=leaderboard_data,
                                chart_data=chart_data,
                                line_chart_data=line_chart_data,
                                sidebar_filter_based_on_requirement=sidebar_filter_based_on_requirement
                            )
    except Exception as e:
        log_error("view", "super_admin", str(e), "dashboard")
        return jsonify({
            "message": str(e),
            "status": "error"
        }), 400

@super_admin.route("/levels")
@required_role_as_super_admin()
def levels():
    session["question_id_list"] = None
    user_data = get_user_document_data(session.get('super_admin_id'))
    try:
        grade = request.args.get("grade")
        grade_dict = next((grade_dict for grade_dict in grade_breakdown if grade_dict.get('grade_number') == int(grade)), None)
        if not grade_dict:
            return jsonify({
                "status": "error",
                "message": "Invalid Grade!"
            }), 400
        chapter = request.args.get("chapter")
        chapter_dict = next((chapter_dict for chapter_dict in grade_dict.get("chapters") if chapter_dict.get('chapter_number') == int(chapter)), None)
        if not chapter_dict:
            return jsonify({
                "status": "error",
                "message": "Invalid Chapter!"
            }), 400
        levels = chapter_dict.get("levels")
        sidebar_filter_based_on_requirement = firebase_get_approved_question_count()
        questions_for_super_admin = sidebar_filter_based_on_requirement.get(f"NCERT_G{int(grade):02}_TOPIC{int(chapter):02}")
        for level in levels:
            level_id = f"NCERT_G{int(grade):02}_TOPIC{int(chapter):02}_LEVEL{int(level.get('level_number')):02}"
            level["questions_for_super_admin"] = questions_for_super_admin.get(level_id) or 0
        return render_template( "/super_admin/level/level.html",
                                levels=levels,
                                chapter_name=chapter_dict.get("chapter_name"),
                                grade=grade,
                                chapter=chapter,
                                grade_breakdown=grade_breakdown,
                                sidebar_filter_based_on_requirement=sidebar_filter_based_on_requirement
                            )
    except ValueError as e:
        log_error("view", "super_admin", str(e), "levels")
        return jsonify({
            "status": "error",
            "message": "Do not tamper with the URL. Go to dashboard and try again!"
        }), 400

@super_admin.route("/review-question")
@required_role_as_super_admin()
def review_question():
    user_data = get_user_document_data(session.get('super_admin_id'))
    try:
        grade = int(request.args.get("grade"))
        chapter = int(request.args.get("chapter"))
        level = int(request.args.get("level"))
        document_id = request.args.get("document_id")
        if not all((grade, chapter, level)):
            return jsonify({
                "status": "error",
                "message": "Do not tamper with the URL. Go to dashboard and try again!"
            })
        if not document_id:
            question_document_ids = firebase_get_questions_for_super_admin_list(grade, chapter, level)
            if len(question_document_ids) == 0:
                return jsonify({
                    "status": "error",
                    "message": "No questions for super admin!"
                }), 400
            session["question_id_list"] = question_document_ids
        question_document_list = session.get("question_id_list")
        if not question_document_list:
            return redirect(url_for("super_admin.dashboard"))
        elif len(question_document_list) == 0:
            return jsonify({
                "status": "error",
                "message": "No questions for review!"
            }), 400
        if not document_id:
            document_id = question_document_list[0]
        try:
            next_document_id = question_document_list[question_document_list.index(document_id) + 1]
        except IndexError:
            next_document_id = ""
        question_data = firebase_get_question(document_id, grade, chapter, level)
        admin_name = question_data.get("approved_by")
        grade_dict, chapter_dict, level_dict = get_grade_breakdown_dict(grade, chapter, level)
        sidebar_filter_based_on_requirement = firebase_get_approved_question_count()
        return render_template( "/super_admin/question/review_question.html",
                                grade=grade,
                                chapter=chapter,
                                level=level,
                                level_name=level_dict.get("level_name"),
                                grade_breakdown=grade_breakdown,
                                next_document_id=next_document_id,
                                document_id=document_id,
                                question_data=question_data,
                                pdf_url=chapter_dict.get("chapter_pdf"),
                                admin_name=admin_name,
                                formula_list=formula_list,
                                sidebar_filter_based_on_requirement=sidebar_filter_based_on_requirement
                            )
    except ValueError as e:
        log_error("view", "super_admin", str(e), "review_question")
        return jsonify({
            "status": "error",
            "message": "Do not tamper with the URL. Go to dashboard and try again!"
        }), 400

@super_admin.route("/student-reported")
@required_role_as_super_admin()
def student_reported():
    user_data = get_user_document_data(session.get('super_admin_id'))
    try:
        if not session.get("student_reported_list"):
            question_document_ids = firebase_get_questions_student_reported()
            if len(question_document_ids) == 0:
                return jsonify({
                    "status": "error",
                    "message": "No questions for super admin!"
                }), 400
            session["student_reported_list"] = question_document_ids
        student_reported_list = session.get("student_reported_list")
        if not student_reported_list:
            return redirect(url_for("super_admin.dashboard"))
        elif len(student_reported_list) == 0:
            return jsonify({
                "status": "error",
                "message": "No questions for review!"
            }), 400
        document_id = student_reported_list[0]
        document_id = document_id.get("id")
        question_data, grade, chapter, level = firebase_get_question_from_main(document_id)
        question_data = question_data.get("data")
        grade_dict, chapter_dict, level_dict = get_grade_breakdown_dict(grade, chapter, level)
        sidebar_filter_based_on_requirement = firebase_get_approved_question_count()
        return render_template( "/super_admin/reported_questions/student_reported/student_reported.html",
                                grade=grade,
                                chapter=chapter,
                                level=level,
                                level_name=level_dict.get("level_name"),
                                grade_breakdown=grade_breakdown,
                                document_id=document_id,
                                question_data=question_data,
                                formula_list=formula_list,
                                sidebar_filter_based_on_requirement=sidebar_filter_based_on_requirement,
                                total_questions=len(student_reported_list)
                            )
    except ValueError as e:
        log_error("view", "super_admin", str(e), "student_reported")
        return jsonify({
            "status": "error",
            "message": "Do not tamper with the URL. Go to dashboard and try again!"
        }), 400


@super_admin.route("/teacher-reported")
@required_role_as_super_admin()
def teacher_reported():

app/templates/super_admin/main.jinja
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;900&display=swap" rel="stylesheet">

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/8.11.8/sweetalert2.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include("super_admin/main_script.jinja") %}
    {% include("super_admin/main_style.jinja") %}

  </head>
  <body>
    <div class="main-container">
      <nav class="navbar fixed-top navbar-expand navbar-light" style="background: white;">
        <a href="#menu-toggle" id="menu-toggle" class="navbar-brand">
          <span class="navbar-toggler-icon"></span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample02">
          <a class="navbar-brand" href="/">
            <img src="/static/images/logo.png" width="30em" />
            <span style="font-size: 1em; color: black;"><b>PixelEditor</b></span>
          </a>
          <ul class="nav navbar-nav ml-auto">
              <li class="nav-item" id="student_reported_navigator">
                  <a class="nav-link" href="{{url_for('super_admin.student_reported')}}">Student Reported</a>
              </li>
              <li class="nav-item" id="teacher_reported_navigator">
                  <a class="nav-link" href="{{url_for('super_admin.teacher_reported')}}">Teacher Reported</a>
              </li>
              <li class="nav-item" id="dashboard_navigator">
                  <a class="nav-link" href="{{url_for('super_admin.dashboard')}}">Dashboard</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="#" onclick="logout_user()">Logout</a>
              </li>
          </ul>
          <form class="form-inline my-2 my-md-0"> </form>
        </div>
      </nav>
      <div id="wrapper" class="toggled">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
          <ul class="sidebar-nav">
            {% for grade_dict in grade_breakdown %}
              <li data-toggle="collapse" data-target="#grade_{{grade_dict.get('grade_number')}}_menu" class="collapsed">
                  <a class="navbar-grade" href="#"><i class="fa fa-book" aria-hidden="true" style="margin-left: -1.5em;padding-right: 1em;"></i> Grade {{grade_dict.get('grade_number')}} <i class="fa fa-caret-down" aria-hidden="true" style="position: absolute; right: 1em; padding-top: 0.75em;"></i></a>
              </li>
              <ul class="sub-menu collapse" id="grade_{{grade_dict.get('grade_number')}}_menu" style="margin-left: -2.5em;">
                {% for chapter_dict in grade_dict.get("chapters") %}
                  {% set ns = namespace(super_admin=false) %}
                  {% for level_id, questions_for_review in sidebar_filter_based_on_requirement.get("NCERT_G{:02}_TOPIC{:02}".format(grade_dict.get('grade_number'), chapter_dict.get('chapter_number'))).items() %}
                    {% if questions_for_review > 0 %}
                      {% set ns.super_admin=True %}
                    {% endif %}
                  {% endfor %}
                  {% if ns.super_admin %}
                    <li style="list-style: none; padding-left: 2em;"><a style="text-indent: initial;" href="{{url_for('super_admin.levels')}}?grade={{grade_dict.get('grade_number')}}&chapter={{chapter_dict.get('chapter_number')}}">{{chapter_dict.get("chapter_name")}}</a></li>
                  {% endif %}
                {% endfor %}
              </ul>
            {% endfor %}
          </ul>
        </div>
        <div id="page-content-wrapper">
          <div class="container-fluid">
            {% block main %}{% endblock %}
          </div>
          <div class="container-fluid mt-5 text-center">
            <div class="row footer-container p-5" id="footer">
              <div class="col">
                <nav class="navbar navbar-expand" style="justify-content:center">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <i class="fab fa-facebook" style="font-size:40px"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://twitter.com/PixelMath">
                                <i class="fab fa-twitter" style="font-size:40px"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://www.instagram.com/pixel_math/">
                                <i class="fab fa-instagram" style="font-size:40px"></i>
                            </a>
                        </li>
                    </ul>
                </nav>
                <p id='footer-copyright' class="mt-4">Copyright &copy; 2019 PixelMath | Powered by CreatorsInk</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="loader">
      <img src="/static/images/loading.gif" class="loading-gif">
    </div>
  </body>
</html>

app/templates/super_admin/main_script.jinja
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    messageStyle: 'none',
    extensions: ['text2jax.js'],
    jax: ['input/TeX', 'output/HTML-CSS'],
    tex2jax: {
      inlineMath: [['$', '$'], ['\\(', '\\)']],
      displayMath: [['$$', '$$'], ['\\[', '\\]']],
      processEscape: true,
      ignoreClass: "note-editable"
    },
    TeX: {
      extensions: ['AMSmath.js', 'AMSsymbols.js', 'noErrors.js', 'noUndefined.js']
    }
  });
  MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
</script>
<script>
  $(document).ready(function(){
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
    function detectMob() {
      const toMatch = [
        /Android/i,
        /webOS/i,
        /iPhone/i,
        /iPad/i,
        /iPod/i,
        /BlackBerry/i,
        /Windows Phone/i
      ];
      return toMatch.some((toMatchItem) => {
        return navigator.userAgent.match(toMatchItem);
      });
    }
    let is_mobile = detectMob();
    if (is_mobile) {
      $('body').empty();
      let html = `
                    <style>
                      body {
                        background-color: #eaf8fe;
                      }
                      * {
                        font-family: 'Comfortaa', Helvetica, Arial;
                      }
                    </style>
                    <div class="col-sm-12 col-md-12 col-lg-12 mt-5 text-center">
                      <span style="font-size: 3em; color: #656b6a;">PixelEditor</span>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-12 text-center mt-5">
                      <img src="/static/images/not_supported.gif" style="width: 50%; height: auto;">
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-12 mt-5">
                      <h3 style="color: #656b6a;">This website does not support mobile! Please use a desktop.</h3>
                    </div>
                `
      $("body").append(html)
    }
    $(".sidebar-nav li").click(function(){
      $(".sidebar-nav li").removeClass('active')
      $(this).addClass("active");
    })
    $("#menu-toggle").click(function(){
      if ($("#wrapper").hasClass("toggled")) {
        $("#page-content-wrapper").css("width", (window.innerWidth-250).toString()+"px")
      } else {
        $("#page-content-wrapper").css("width", (window.innerWidth).toString()+"px")
      }
    })
    $("#menu-toggle").click()
    $("#menu-toggle").click()
  })
  function logout_user() {
    $.ajax({
      url: "{{url_for('super_admin_api.logout')}}",
      type: 'post',
      beforeSend: function(){
        $('.main-container').addClass('blur');
        $(':button').prop('disabled', true);
        $("#loader").show();
      },
      success: function (result) {
        window.location.href = "{{url_for('super_admin.login')}}";
      },
      error: function (result) {
        alert(result.responseJSON.message);
      },
      complete:function(data){
        $('.main-container').removeClass('blur');
        $(':button').prop('disabled', false);
        $("#loader").hide();
      }
    });
  }
</script>

app/templates/super_admin/main_style.jinja
<style>
  body {
      direction: ltr;
      text-align:left;
      background-color: #f0f1f3;
      font-family: 'Roboto', sans-serif;
  }
   body {
    overflow-x: hidden;
  }
  #wrapper {
    padding-left: 0;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
  }
  #wrapper.toggled {
    padding-right: 250px;
  }
  #sidebar-wrapper {
    z-index: 1000;
    position: fixed;
    top: 3.5em;
    left: 0px;
    width: 0;
    height: 100%;
    margin-right: -250px;
    overflow-y: auto;
    background: #fff;
    margin-top: 5px;
    border-radius: 0 1em 0 0;
    -webkit-transition: all 0.5s ease;
    -moz-transition: all 0.5s ease;
    -o-transition: all 0.5s ease;
    transition: all 0.5s ease;
  }
  #wrapper.toggled #sidebar-wrapper {
    width: 250px;
  }
  #page-content-wrapper {
    margin-top: 3.5em;
    position: absolute;
    padding: 15px;
  }
  #wrapper.toggled #page-content-wrapper {
    margin-top: 3.5em;
    position: absolute;
    margin-left: 250px;
  }
  .sidebar-nav {
    position: absolute;
    top: 0;
    width: 250px;
    margin: 0;
    padding: 0;
    list-style: none;
    margin-bottom: 20vh;
  }
  .sidebar-nav li {
    text-indent: 20px;
    line-height: 40px;
  }
  .sidebar-nav li.active a {
    color: #5dca88;
    font-weight: 900;
  }
  .sidebar-nav li:hover {
    background: #eee;
  }
  .sidebar-nav li a {
    display: block;
    text-decoration: none;
    color: #a6acc2;
  }
  .sidebar-nav li a:hover {
    text-decoration: none;
    color: #000;
    background: #eee;
  }
  .sidebar-nav li a:active, .sidebar-nav li a:focus {
    text-decoration: none;
  }
  .blur {
    filter: blur(5px);
    -webkit-filter: blur(5px);
    -moz-filter: blur(5px);
    -o-filter: blur(5px);
    -ms-filter: blur(5px);
  }
  #loader {
    position: fixed;
    display: none;
    align-items: center;
    width: 50%;
    top: 30%;
    left: 35%;
    z-index: 999;
  }
  .loading-gif {
    width: 50%;
    height: auto;
  }
  .navbar-light .navbar-nav .active>.nav-link, .navbar-light .navbar-nav .nav-link.active, .navbar-light .navbar-nav .nav-link.show, .navbar-light .navbar-nav .show>.nav-link {
    color: #5dca88;
  }
  .navbar-light .navbar-nav .nav-link {
    color: black;
  }
  #footer .nav-link {
    color: black;
  }
  #footer .nav-link:hover {
    color: #3d3d3d;
  }
  #footer-copyright {
    font-size:11px;
    font-weight: bold;
    text-align:center;
    padding-bottom: 10px;
  }
  .white-container {
    background: white;
    border-radius: 1em;
    box-shadow: 0px 5px 10px #eee;
  }
  .overlap-box {
    position: absolute;
    width: 3em;
    height: 3em;
    right: 0;
    top: 0;
    border-radius: 0em 1em;
  }
  .heavy-font {
    font-weight: 900;
  }
  button {
    border: none;
  }
</style>